version: "3.8"

services:
  email-service:
    container_name: email-service
    build:
      context: .  # Указываем, что контекст сборки это корень проекта
      dockerfile: Dockerfile  # Указываем путь до Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - cmd/email-service/.env
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
    restart: always
