name: Deploy Tama Services

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image
        run: |
          docker build -t tama-services:latest .

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
          docker stop tama-services || true
          docker rm tama-services || true
          docker rmi tama-services:latest || true
          exit
          EOF

      - name: Transfer Docker Image
        run: |
          docker save tama-services:latest | ssh -o StrictHostKeyChecking=no aka_curiosity@176.108.254.11 docker load

      - name: Start Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
          docker run -d --name tama-services -p 8081:8081 tama-services:latest
          EOF
